import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.metrics import (
    precision_recall_curve,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
    auc,
)


def find_optimal_threshold(csv_file, output_folder="images"):
    """
    Analyzes model performance by comparing software predictions against human validation.
    It calculates the Precision-Recall curve to find the distance threshold that
    maximizes the F1-Score and generates a comparison report.
    """
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # 1. Load CSV Data
    try:
        df = pd.read_csv(csv_file, encoding="utf-8")
    except:
        # Fallback for files with different encoding (common with Excel exports)
        df = pd.read_csv(csv_file, encoding="latin-1")

    # 2. Strict Column Cleanup
    # Standardize text columns to uppercase for consistent comparison
    for col in ["Exploration", "Human_validation", "Status"]:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip().str.upper()

    # Convert Distance metric to numeric, turning errors into NaNs
    df["Distance"] = pd.to_numeric(df["Distance"], errors="coerce")

    # 3. Filtering
    # Only keep rows that have been explored and have a valid distance value
    df = df[df["Exploration"] == "TRUE"].copy()
    df = df.dropna(subset=["Distance"])

    if df.empty:
        print("❌ Error: No valid data found after filtering.")
        return None

    # 4. MAPPING (y_true: Human Ground Truth | y_pred_initial: Software Logic)
    # Convert text labels into binary integers (1 for Anomaly, 0 for Normal)
    y_true = (
        df["Human_validation"].map({"TRUE": 1, "FALSE": 0}).fillna(0).astype(int).values
    )
    y_pred_initial = (
        df["Status"].map({"ANOMALIE": 1, "RAS": 0}).fillna(0).astype(int).values
    )

    distances = df["Distance"].values

    # --- CALCULATE BASELINE PERFORMANCE (Before Optimization) ---
    f1_before = f1_score(y_true, y_pred_initial, zero_division=0)
    precision_before = precision_score(y_true, y_pred_initial, zero_division=0)
    recall_before = recall_score(y_true, y_pred_initial, zero_division=0)

    # 5. CALCULATE PRECISION-RECALL CURVE FOR OPTIMIZATION
    # This computes precision and recall for every possible threshold in the distance data
    precisions, recalls, thresholds = precision_recall_curve(y_true, distances)

    # Calculate F1-score for each threshold: F1 = 2 * (P * R) / (P + R)
    f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-10)

    # Locate the index of the highest F1-score to find the best threshold
    ix = np.argmax(f1_scores)
    best_threshold = thresholds[ix] if ix < len(thresholds) else thresholds[-1]

    # Calculate predictions using the new optimal threshold
    y_pred_opti = (distances >= best_threshold).astype(int)
    f1_after = f1_score(y_true, y_pred_opti, zero_division=0)

    # 6. DISPLAY COMPARATIVE RESULTS
    print(f"🔍 Number of samples analyzed: {len(df)}")

    print("\n" + "=" * 45)
    print("📊 CURRENT PERFORMANCE (Fixed Software Threshold)")
    print("=" * 45)
    print(
        classification_report(
            y_true, y_pred_initial, target_names=["NORMAL", "ANOMALY"], zero_division=0
        )
    )
    print(f"-> Current F1-Score: {f1_before:.2%}")

    print("\n" + "=" * 45)
    print(f"🚀 OPTIMAL PERFORMANCE (Suggested Threshold: {best_threshold:.4f})")
    print("=" * 45)
    print(
        classification_report(
            y_true, y_pred_opti, target_names=["NORMAL", "ANOMALY"], zero_division=0
        )
    )

    print("-" * 45)
    print(f"📈 F1-SCORE IMPROVEMENT: {f1_before:.2%} ➡️ {f1_after:.2%}")
    print(f"✅ PR-AUC (Area Under Curve): {auc(recalls, precisions):.4f}")
    print("-" * 45)

    # 7. VISUALIZATION
    # Plot the evolution of the F1-Score relative to the distance threshold
    plt.figure(figsize=(10, 6))
    plt.plot(thresholds, f1_scores[:-1], color="orange", lw=2, label="F1-Score Curve")
    plt.axvline(
        best_threshold,
        color="red",
        linestyle="--",
        label=f"Optimal Threshold: {best_threshold:.3f}",
    )

    plt.title(f"Threshold Optimization: Max F1-Score = {f1_after:.2%}")
    plt.xlabel("Distance Threshold")
    plt.ylabel("F1-Score")
    plt.legend()
    plt.grid(True, alpha=0.3)

    # Save the plot for documentation or reports
    plt.savefig(f"{output_folder}/f1_comparison.png")
    plt.close()

    print(f"\n✅ Graph saved in '{output_folder}/f1_comparison.png'")
    return best_threshold


if __name__ == "__main__":
    # Path to the report generated by the validation tool
    CSV_FILE = "../results/cosine_final_synced.csv.csv"

    if os.path.exists(CSV_FILE):
        find_optimal_threshold(CSV_FILE)
    else:
        print(f"❌ File not found: {CSV_FILE}")
